<?php

namespace Database\Seeders;

use App\Models\Job;
use Illuminate\Database\Seeder;

class JobSeeder extends Seeder
{
    public function run(): void
    {
        Job::query()->insert([
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نویس iOS'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'Full Stack'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'Java developer'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'تولید محتوا'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نویس وب'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نویس بک اند'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نویس جاوا'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'Front end'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیر دیجیتال مارکتینگ'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'DevOps'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس دیجیتال مارکتینگ'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'help desk'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'پشتیبان محصولات امنیتی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس امنیت شبکه'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس عملیات'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نویس Go'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس ارشد مارکتینگ'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس بازاریابی دیجیتال'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس تبلیغات کلیکی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نویس'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نویس PHP'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس پشتیبانی شبکه'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس برنامه ریزی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس IT'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'طراح محصول'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس دیتابیس'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'حسابدار'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارآموز'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نویس اندروید'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیر توسعه و طراحی سازمانی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس ارشد امنیت'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه ویسی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مهندس نرم افزار'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس شبکه'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مالک محصول'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'طراح رابط کاربری UI & UX'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیر راهبردی بازاریابی و فروش'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارآموز لاراول'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس ارشد فنی لینوکس'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'data scientist'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'React Native developer'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'Network Specialist'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'فول استک'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'فول استک ودیتابیس'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'Software Developer'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیر اجرایی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس منابع انسانی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'System Admin'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نویس پایتون'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیر سیستم در CDN'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس ارشد شبکه'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'تحقیق و توسعه'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'تست نرم افزار '],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نویس c#'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'soc'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'تخصص مخفی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'منشی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس پشتیبانی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیریت محصول'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیر کمپین'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'فرانت اند'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نویس موبایل'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'دیجیتال مارکتینگ'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نویس فرانت اند'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کاراموز'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس soc سطح یک'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'تیم اجرایی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'Android Developer'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'طراح سایت'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'طراح گرافیک'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نویس فلاتر'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'توسعه کسب و کار'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس سئو'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'تحلیلگر'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارآموز وب'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'منایع انسانی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'BI Expert'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'توسعه دهنده جاوا'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس فروش و بازاریابی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'دیتا آنالیست'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس مارکتینگ'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'ناشناس'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مخفی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس ارشد It'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیر جبران خدمات و مزایا'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس فروش'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'توسعه دهنده'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیر بازاریابی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'سایر'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نویس بازی - یونیتی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیر محصول'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'Front end Developer'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'Back end'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نویس جنگو'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نویس ارشد'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیر برند'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'استقرار'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیر روابط عمومی تجاری'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیر محتوا - دیجیتال مارکتینگ'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس تبلیغات'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'gis'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیر پروژه'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'Account Manager'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیر توسعه کسب و کار'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نویس,DevOps, کانفیگ و مدیریت سرورها'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'فروش'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نویس انگولار'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'متخصص هوش مصنوعی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نویس فول استک'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس سیستم ها و روش ها'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس تولید و مدیریت محتوا'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس تست نرم افزار'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس طراحی سایت'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'اسکرام مستر'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مسئول دفتر'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'اکانت منیجر'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'اداری'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس ترابری'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس کنترل پروژه'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'پژوهشگر پردازش تصویر'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'voip engineer'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس آی تی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'معاون مدیر فنی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیر فنی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'توسعه دهنده Miicrosoft Dynamics CRM'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس نرم افزار'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'Data Analyst'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'ITIL Expert'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مهندسی شیمی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیر محتوا'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیر تبلیغات'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس فرآیند'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'گرافیست'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نویس React'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'فروش سازمانی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارمند فروش'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'فرانت اند دولوپر'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کنترل کیفیت'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیر IT'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'فروش خارجی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس فروش سازمانی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارآموز برنامه نویسی وب'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس پروژه'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نويس'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'سرپرست مالی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نویس full stack وب'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس فنی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیر شبکه'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'Devops Engineer'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس جذب و استخدام حوزه IT'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'cto'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'linux system administrator'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارمندفروش و بازاریابی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس معمار'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارمند'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس تولید محتوای سینمایی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'تحلیل‌گر کسب‌وکار / سیستم'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'Full Stack Developer'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارمند اداری'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیر منابع انسانی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کال سنتر'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'بانکدار'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'روابط عمومی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'پشتیبانی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدير ديجيتال ماركتينگ'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'طراح رابط کاربری'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیریت واحد فروش'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس مانیتورینگ'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیرپروژه'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس واحد فنی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'پشتیبان هاستینگ'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'موشن گرافیست'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'Datacenter engineer'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس شبکه وایرلس'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'واحد پشتیبانی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'Operation specialist'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیر فروش'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'پشتیبان فنی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مسئول اجرایی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس تیم نرم افزار'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس تولید محتوا'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس اداری'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'Senior Front-End Developer'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس ارشد فروش'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'استراتژیست بازاریابی محتوا'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مهندس فنی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'طراح صنعتی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'نیروی فنی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیر تدارکات'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس پشتیبانی فنی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'پشتیبانی صبح'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس شبکه‌های اجتماعی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'خبرنگار'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مشاور و کارشناس'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'Software Engineer'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'ویراستار'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'سخت افزار و نرم افزار'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس فروش فروشگاه زنجیره ای'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'تحلیل گر داده'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'بازرگانی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'تدارکات'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'React Native and React Developer'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'منابع انسانی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'كارشناس مانيتورينگ'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'طراح مدل های سه بعدی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس مالی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => '3D آرتیست'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس شیمی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مهندس فروش'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'بازرس'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیر شعبه'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'بازاریاب ( فروش محصولات - جذب فریلنسر )'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'پروموتر'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس فناوری اطلاعات'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مربی کودکان'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'manager'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'موشن گرافست'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'آرایشگر'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارمند مرکز تماس'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'پسیو کار'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'programmer'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مسئول فنی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مترجم'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مهندس سخت افزار'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نویس وب، مالک محصول'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'پشتیبان سایت'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مشاور تحصیلی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'توسعه دهنده iOS'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'ستادی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیر پروژه سئو'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس CRM'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'سرپرست'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'تحلیلگر مالی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس تست نفوذ'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارآموز سئو'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مدیر'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه ارشد'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارمند ارشد'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نویس QML'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'بازاریاب,فریلنسر,تولیدمحتوا,پروژه گرافیکی,و...'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'بازاریاب'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'كارمند'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'بازاریابی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'رییس حسابداری'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'Noc'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'طراح و معمار'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'Game engine programmer'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'همکار بخش فنی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس مرکز تماس'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'سرپرست مرکز تماس'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کارشناس فروش تلفنی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'امنیت نرم افزار'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'كارشناس منابع انساني'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کپی رایتر'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مشتری بازدید ایده'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'سایت شخصی'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'نویسنده'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نویس ویندوز'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'برنامه نویس بک اند و فرانت'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'توسعه‌دهنده‌ی C++'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مهندس'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'مشتری دائمی 7 ساله'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'Full Stack-Project Manager'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'نیروی اداری'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'کدنویس'],
            ['created_at' => now(), 'updated_at' => now(), 'title' => 'معلم رباتیک']
        ]);
    }
}
